### ISSUE TITLE
"log in to confirm your age" 

### ISSUE THREAD

**Issue by Ventority** [L0um15/SpotiSharp#8]
**Describe the bug**
Getting this error by youtube when trying to download some songs.

**How To Reproduce**
(in cmd) SpotiSharp.exe https://open.spotify.com/track/274tSPavv09i163nBnYrCU?si=2I7lhKahSlGWC7gKdQr-ww

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

I know this could be hard to be fixed but it is more or less necessary because you can't download playlists completely if there is a song like this inside.
(sorry for my poor english :D)

**Comment by L0um15** [comment]
Thanks for your issue report. I'll try to fix this as quickly as i can.

**Comment by L0um15** [comment]
Good news: I was able to download your track!
![obraz](https://user-images.githubusercontent.com/44427021/107816483-20926b80-6d75-11eb-9353-260b25823b7c.png)

Spotisharp was getting only first occurance from the first page instead of all occurances.
Now it will read whole page and iterate one by one if previous link is not available due to some restrictions. This is not ideal workaround but still it is better than nothing.

Theoretically i could just use login credentials to bypass age restriction but this will require oauth2 key which i cant share in public due to security reasons.

Fix will be released shortly after closing this issue.

**Comment by L0um15** [comment]
I consider this issue as fixed. Feel free to reopen this issue if problem persists. Don't forget to leave a star if you enjoy using my software 👍
